# Global Configuration

# Base Paths (relative to project root)
data_dir: data
raw_data_dir: data/01_raw/eyepac-light-v2-512-jpg
conformed_data_dir: data/02_conformed_to_imagefolder
train_model_dir: data/03_train_model
evaluate_dir: data/04_evaluate
predict_dir: data/05_predict
predict_default_input_dir: data/05_predict/inference_input_default_dataset
results_dir: results/mobilenetv3  # Legacy path, some code may still use this
log_dir: logs
training_log_dir: logs/training/mobilenetv3

# Data Handling & Model Parameters
image_size: 512
imagenet_mean: [0.485, 0.456, 0.406]
imagenet_std: [0.229, 0.224, 0.225]
num_classes: 2 # NRG, RG
model_name: mobilenetv3

# Default Training Parameters (can be overridden by phase-specific config)
batch_size: 4
num_epochs: 6 # Default number of epochs from first training run was 6
learning_rate: 0.001
optimizer: Adam
scheduler: StepLR
scheduler_step_size: 3
scheduler_gamma: 0.1
loss_function: CrossEntropyLoss

# Default Transform Parameters (can be overridden by phase-specific config)
add_noise_level: 0.01
color_jitter_brightness: 0.01
color_jitter_contrast: 0.01
color_jitter_saturation: 0.01
color_jitter_hue: 0.01
random_rotation_degrees: 0 
random_affine_degrees: 0 

# Other settings
num_workers: 1 
pin_memory: True 
